'use client'

import type { Metadata } from "next";
import { Header } from "@/component/Layouts/header";
import { ReactQueryClientProvider } from "@/component/ReactQueryClientProvider";
import { Providers } from "./providers";
import Preloader from '@/component/preloader/preloader';
import { useEffect, useState } from 'react';
import './globals.css';
import "../css/styles.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulasikan loading delay, bisa diganti logika nyata
    const timer = setTimeout(() => setLoading(false), 1500);
    return () => clearTimeout(timer);
  }, []);

  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body>
          <Providers>
            {loading ? ( <Preloader /> ) : ( 
            <div className="pb-8 w-full">
              <Header />
            </div>
            )}
            <main>
              {children}
            </main>
          </Providers>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
